def ref_info(self):
    info = {
        'Evapotranspiration': {
            'GLEAM_hybird_PLUMBER2': {
                'GLEAM_hybird_PLUMBER2_timezone': 0.0,
                'GLEAM_hybird_PLUMBER2_data_type': 'stn',
                'GLEAM_hybird_PLUMBER2_data_groupby': 'Single',
                'GLEAM_hybird_PLUMBER2_dir': '/tera11/zhwei/zhwei/data/Data_ref/stn_ref/Evapotranspiration/GLEAM_hybird_PLUMBER2/',
                'GLEAM_hybird_PLUMBER2_varname': 'Qle_cor',
                'GLEAM_hybird_PLUMBER2_fulllist': '../../CoLM-Evaluation/CoLM-Evaluation_new/lists/ref/LIST_GLEAM_hybird_PLUMBER2_FULL.csv',
                'GLEAM_hybird_PLUMBER2_tim_res': 'Day',
                'GLEAM_hybird_PLUMBER2_varunit': '',
                'GLEAM_hybird_PLUMBER2_geo_res': 0.25,
                'GLEAM_hybird_PLUMBER2_suffix': '',
                'GLEAM_hybird_PLUMBER2_prefix': '',
                'GLEAM_hybird_PLUMBER2_syear': 1980,
                'GLEAM_hybird_PLUMBER2_eyear': 2022,
            },
            'GLEAM_v3.7a_daily': {
                'GLEAM_timezone': 0.0,
                'GLEAM_data_type': 'geo',
                'GLEAM_data_groupby': 'Single',
                'GLEAM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/GLEAM/v3.7a/daily/merged/',
                'GLEAM_varname': 'E',
                'GLEAM_fulllist': '',
                'GLEAM_tim_res': 'Day',
                'GLEAM_varunit': 'mm day -1',
                'GLEAM_geo_res': 0.25,
                'GLEAM_suffix': 'E_',
                'GLEAM_prefix': '_GLEAM_v3.7a_DY',
                'GLEAM_syear': 1980,
                'GLEAM_eyear': 2022,
            },
            'GLEAM_v3.7a_monthly': {
                'GLEAM_timezone': 0.0,
                'GLEAM_data_type': 'geo',
                'GLEAM_data_groupby': 'Single',
                'GLEAM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/GLEAM/v3.7a/monthly/',
                'GLEAM_varname': 'E',
                'GLEAM_fulllist': '',
                'GLEAM_tim_res': 'Month',
                'GLEAM_varunit': 'mm month -1',
                'GLEAM_geo_res': 0.25,
                'GLEAM_suffix': 'E_',
                'GLEAM_prefix': '_GLEAM_v3.7a_MO',
                'GLEAM_syear': 1980,
                'GLEAM_eyear': 2022,
            },
            'GLEAM_v3.7a_yearly': {
                'GLEAM_timezone': 0.0,
                'GLEAM_data_type': 'geo',
                'GLEAM_data_groupby': 'Single',
                'GLEAM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/GLEAM/v3.7a/yearly/',
                'GLEAM_varname': 'E',
                'GLEAM_fulllist': '',
                'GLEAM_tim_res': 'Year',
                'GLEAM_varunit': 'mm year -1',
                'GLEAM_geo_res': 0.25,
                'GLEAM_suffix': 'E_',
                'GLEAM_prefix': '_GLEAM_v3.7a_YR',
                'GLEAM_syear': 1980,
                'GLEAM_eyear': 2022,
            },
            # FIXME: 缺了daily的，不在一个文件夹下面，是否可以合并
            'GLEAM_v3.7b_monthly': {
                'GLEAM_timezone': 0.0,
                'GLEAM_data_type': 'geo',
                'GLEAM_data_groupby': 'Single',
                'GLEAM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/GLEAM/v3.7b/monthly/',
                'GLEAM_varname': 'E',
                'GLEAM_fulllist': '',
                'GLEAM_tim_res': 'Month',
                'GLEAM_varunit': 'mm month -1',
                'GLEAM_geo_res': 0.25,
                'GLEAM_suffix': 'E_',
                'GLEAM_prefix': '_GLEAM_v3.7b_MO',
                'GLEAM_syear': 2003,
                'GLEAM_eyear': 2022,
            },
            'GLEAM_v3.7b_yearly': {
                'GLEAM_timezone': 0.0,
                'GLEAM_data_type': 'geo',
                'GLEAM_data_groupby': 'Single',
                'GLEAM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/GLEAM/v3.7b/yearly/',
                'GLEAM_varname': 'E',
                'GLEAM_fulllist': '',
                'GLEAM_tim_res': 'Year',
                'GLEAM_varunit': 'mm year -1',
                'GLEAM_geo_res': 0.25,
                'GLEAM_suffix': 'E_',
                'GLEAM_prefix': '_GLEAM_v3.7b_YR',
                'GLEAM_syear': 2003,
                'GLEAM_eyear': 2022,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Latent_Heat': {
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/surface_latent_heat_flux/',
                'ERA5LAND_varname': 'slhf',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'w / m2',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_daymean_surface_latent_heat_flux',
                'ERA5LAND_syear': 1970,
                'ERA5LAND_eyear': 2022,
            },
            'FLUXCOM': {
                'FLUXCOM_timezone': 0.0,
                'FLUXCOM_data_type': 'geo',
                'FLUXCOM_data_groupby': 'Single',
                'FLUXCOM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Latent_Heat/FLUXCOM/monthly/',
                'FLUXCOM_varname': 'le',
                'FLUXCOM_fulllist': '',
                'FLUXCOM_tim_res': 'Month',
                'FLUXCOM_varunit': 'watt / m2',
                'FLUXCOM_geo_res': 0.5,
                'FLUXCOM_suffix': 'le',
                'FLUXCOM_prefix': '',
                'FLUXCOM_syear': 1980,
                'FLUXCOM_eyear': 2014,
            },
            'DOLCE': {
                'DOLCE_timezone': 0.0,
                'DOLCE_data_type': 'geo',
                'DOLCE_data_groupby': 'Single',
                'DOLCE_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Latent_Heat/DOLCE/',
                'DOLCE_varname': 'hfls',
                'DOLCE_fulllist': '',
                'DOLCE_tim_res': 'Month',
                'DOLCE_varunit': 'W m -2',
                'DOLCE_geo_res': 0.5,
                'DOLCE_suffix': 'W m-2',
                'DOLCE_prefix': '',
                'DOLCE_syear': 2000,
                'DOLCE_eyear': 2009,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Streamflow': {
            'GRDC': {
                'GRDC_timezone': 0.0,
                'GRDC_data_type': 'stn',
                'GRDC_data_groupby': 'Single',
                'GRDC_dir': '/tera11/zhwei/zhwei/data/Data_ref/stn_ref/StreamFlow/GRDC/',
                'GRDC_varname': 'discharge',
                'GRDC_fulllist': '',  # don't need
                'GRDC_tim_res': 'Month',
                'GRDC_varunit': 'm3 / s',
                'GRDC_geo_res': 0.25,  # don't need
                'GRDC_suffix': '',  # don't need
                'GRDC_prefix': '',  # don't need
                'GRDC_syear': 2002,
                'GRDC_eyear': 2005,
                'GRDC_max_uparea': 50000000000.0,
                'GRDC_min_uparea': 1000.0,
            },

            'others': {
                '_timezone': 0.0,
                '_data_type': 'stn',
                '_data_groupby': 'Single',
                '_dir': '/tera03/zhwei/Validation_Data/stn_obs/StreamFlow/GRDC',
                '_varname': 'discharge',
                '_fulllist': '/GRDC_flx_FULL.csv',
                '_tim_res': 'Month',
                '_varunit': '',
                '_geo_res': 0.25,
                '_suffix': 'a_',
                '_prefix': '_b',
                '_syear': 2000,
                '_eyear': 2002,
                '_max_uparea': 50000000000.0,
                '_min_uparea': 1000.0,
            },
        },
        'Biomass': {
            'XuSaatchi2021': {
                'XuSaatchi2021_timezone': 0.0,
                'XuSaatchi2021_data_type': 'geo',
                'XuSaatchi2021_data_groupby': 'Single',
                'XuSaatchi2021_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Biomass/XuSaatchi2021/yearly/',
                'XuSaatchi2021_varname': 'biomass', #annual carbon density map of global live woody vegetation
                'XuSaatchi2021_fulllist': '',
                'XuSaatchi2021_tim_res': 'Year',
                'XuSaatchi2021_varunit': 'Mg ha -1',
                'XuSaatchi2021_geo_res': 0.5,
                'XuSaatchi2021_suffix': 'XuSaatchi2021',
                'XuSaatchi2021_prefix': '',
                'XuSaatchi2021_syear': 2000,
                'XuSaatchi2021_eyear': 2019,
            },
            'ESACCI': {
                'ESACCI_timezone': 0.0,
                'ESACCI_data_type': 'geo',
                'ESACCI_data_groupby': 'Single',
                'ESACCI_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Biomass/ESACCI/clim/',
                'ESACCI_varname': 'biomass', #Above-ground biomass
                'ESACCI_fulllist': '',
                'ESACCI_tim_res': 'Single',
                'ESACCI_varunit': 'Mg / ha',
                'ESACCI_geo_res': 0.5,
                'ESACCI_suffix': 'Biomass',
                'ESACCI_prefix': '',
                'ESACCI_syear': 2010,
                'ESACCI_eyear': 2010,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Global_Net_Ecosystem_Carbon_Balance': {
            'GCP': {
                'GCP_timezone': 0.0,
                'GCP_data_type': 'stn',
                'GCP_data_groupby': 'Single',
                'GCP_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Global_Net_Ecosystem_Carbon_Balance/GCP/',
                'GCP_varname': 'nbp', #surface_net_downward_mass_flux_of_carbon_dioxide_expressed_as_carbon_due_to_all_land_processes
                'GCP_fulllist': '', # TODO: need list
                'GCP_tim_res': 'Year',
                'GCP_varunit': 'Pg yr -1"',
                'GCP_geo_res': 0.25,
                'GCP_suffix': 'nbp_1959-2016',
                'GCP_prefix': '',
                'GCP_syear': 1959,
                'GCP_eyear': 2016,
            },
            'Hoffman': {
                'Hoffman_timezone': 0.0,
                'Hoffman_data_type': 'stn',
                'Hoffman_data_groupby': 'Single',
                'Hoffman_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Global_Net_Ecosystem_Carbon_Balance/Hoffman/',
                'Hoffman_varname': 'nbp',
                'Hoffman_fulllist': '',
                'Hoffman_tim_res': 'Year',
                'Hoffman_varunit': 'Pg yr -1',
                'Hoffman_geo_res': 0.25,
                'Hoffman_suffix': 'nbp_1850-2010',
                'Hoffman_prefix': '',
                'Hoffman_syear': 2000,
                'Hoffman_eyear': 2001,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Gross_Primary_Productivity': {
            'FLUXCOM': {
                'FLUXCOM_timezone': 0.0,
                'FLUXCOM_data_type': 'geo',
                'FLUXCOM_data_groupby': 'single',
                'FLUXCOM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Gross_Primary_Productivity/FLUXCOM/',
                'FLUXCOM_varname': 'gpp',
                'FLUXCOM_fulllist': '',
                'FLUXCOM_tim_res': 'Month',
                'FLUXCOM_varunit': 'g / m 2 / day',
                'FLUXCOM_geo_res': 0.5,
                'FLUXCOM_suffix': 'gpp',
                'FLUXCOM_prefix': '',
                'FLUXCOM_syear': 1980,
                'FLUXCOM_eyear': 2014,
            },
            'WECANN': {
                'WECANN_timezone': 0.0,
                'WECANN_data_type': 'geo',
                'WECANN_data_groupby': 'single',
                'WECANN_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Gross_Primary_Productivity/WECANN/',
                'WECANN_varname': 'gpp',
                'WECANN_fulllist': '',
                'WECANN_tim_res': 'Month',
                'WECANN_varunit': 'g / m 2 / day',
                'WECANN_geo_res': 0.25,
                'WECANN_suffix': 'gpp',
                'WECANN_prefix': '',
                'WECANN_syear': 2007,
                'WECANN_eyear': 2015,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Ecosystem_Respiration': {
            'FLUXCOM': {
                'FLUXCOM_timezone': 0.0,
                'FLUXCOM_data_type': 'geo',
                'FLUXCOM_data_groupby': 'Single',
                'FLUXCOM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Ecosystem_Respiration/FLUXCOM/',
                'FLUXCOM_varname': 'reco',
                'FLUXCOM_fulllist': '',
                'FLUXCOM_tim_res': 'Month',
                'FLUXCOM_varunit': 'g m-2 day-1"',
                'FLUXCOM_geo_res': 0.5,
                'FLUXCOM_suffix': 'reco',
                'FLUXCOM_prefix': '',
                'FLUXCOM_syear': 1980,
                'FLUXCOM_eyear': 2013,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Soil_Carbon': {
            'HWSD': {
                'HWSD_timezone': 0.0,
                'HWSD_data_type': 'geo',
                'HWSD_data_groupby': 'Single',
                'HWSD_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Soil_Carbon/HWSD/',
                'HWSD_varname': 'cSoilAbove1m',
                'HWSD_fulllist': '',
                'HWSD_tim_res': 'Year',
                'HWSD_varunit': 'kg / m2',
                'HWSD_geo_res': 0.5,
                'HWSD_suffix': 'soilc_0.5x0.5',
                'HWSD_prefix': '',
                'HWSD_syear': 2000,
                'HWSD_eyear': 2000,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Nitrogen_Fixation': {
            'Davies-Barnard': {
                'Davies-Barnard_timezone': 0.0,
                'Davies-Barnard_data_type': 'geo',
                'Davies-Barnard_data_groupby': 'Single',
                'Davies-Barnard_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Nitrogen_Fixation/Davies-Barnard/',
                'Davies-Barnard_varname': 'fBNF',
                'Davies-Barnard_fulllist': '',
                'Davies-Barnard_tim_res': '',
                'Davies-Barnard_varunit': 'kg m-2 s-1',
                'Davies-Barnard_geo_res': 0.5,
                'Davies-Barnard_suffix': 'fBNF_0.5x0.5',
                'Davies-Barnard_prefix': '',
                'Davies-Barnard_syear': 2000,
                'Davies-Barnard_eyear': 2000,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Runoff': {
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/total_runoff/',
                'ERA5LAND_varname': 'ro',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'm',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_runoff_',
                'ERA5LAND_prefix': '',
                'ERA5LAND_syear': 2000,
                'ERA5LAND_eyear': 2001,
            },
            'LORA': {
                'LORA_timezone': 0.0,
                'LORA_data_type': 'geo',
                'LORA_data_groupby': 'Single',
                'LORA_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Runoff/LORA/',
                'LORA_varname': 'mrro',
                'LORA_fulllist': '',
                'LORA_tim_res': 'Month',
                'LORA_varunit': 'kg m-2 s-1',
                'LORA_geo_res': 0.5,
                'LORA_suffix': 'LORA',
                'LORA_prefix': '',
                'LORA_syear': 1980,
                'LORA_eyear': 2012,
            },
            'GRFR': {
                'GRFR_timezone': 0.0,
                'GRFR_data_type': 'geo',
                'GRFR_data_groupby': 'Year',
                'GRFR_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Runoff/GRFR/',
                'GRFR_varname': 'ro',
                'GRFR_fulllist': '',
                'GRFR_tim_res': 'Day',
                'GRFR_varunit': 'mm',
                'GRFR_geo_res': 0.05,
                'GRFR_suffix': 'RUNOFF_',
                'GRFR_prefix': '',
                'GRFR_syear': 1979,
                'GRFR_eyear': 2019,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Inundation': {
            'grdarea': {
                'grdarea_timezone': 0.0,
                'grdarea_data_type': 'geo',
                'grdarea_data_groupby': 'Single',
                'grdarea_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Inundation/grdarea/',
                'grdarea_varname': 'lev',
                'grdarea_fulllist': '',
                'grdarea_tim_res': 'Year',
                '_varunit': '',
                'grdarea_geo_res': '0.1min', #TODO: 这种1min的分辨率要设置一下怎么做
                'grdarea_suffix': 'grdare_01min',
                'grdarea_prefix': '',
                'grdarea_syear': 2000,
                'grdarea_eyear': 2000,
            },
            # 'GSWO_2023': {
            #     'GSWO_2023_timezone': 0.0,
            #     'GSWO_2023_data_type': '',
            #     'GSWO_2023_data_groupby': '',
            #     'GSWO_2023_dir': '/tera11/zhwei/zhwei/Data_ref/geo/',
            #     'GSWO_2023_varname': '',
            #     'GSWO_2023_fulllist': '',
            #     'GSWO_2023_tim_res': '',
            #     '_varunit': '',
            #     'GSWO_2023_geo_res': 0.25,
            #     'GSWO_2023_suffix': '',
            #     'GSWO_2023_prefix': '',
            #     'GSWO_2023_syear': 2000,
            #     'GSWO_2023_eyear': 2001,
            # },
            # 'GSWO_Pekel_2016': {
            #     'GSWO_Pekel_2016_timezone': 0.0,
            #     'GSWO_Pekel_2016_data_type': '',
            #     'GSWO_Pekel_2016_data_groupby': '',
            #     'GSWO_Pekel_2016_dir': '/tera11/zhwei/zhwei/Data_ref/geo/',
            #     'GSWO_Pekel_2016_varname': '',
            #     'GSWO_Pekel_2016_fulllist': '',
            #     'GSWO_Pekel_2016_tim_res': '',
            #     '_varunit': '',
            #     'GSWO_Pekel_2016_geo_res': 0.25,
            #     'GSWO_Pekel_2016_suffix': '',
            #     'GSWO_Pekel_2016_prefix': '',
            #     'GSWO_Pekel_2016_syear': 2000,
            #     'GSWO_Pekel_2016_eyear': 2001,
            # },
            'GIEMS_v2_2020': {
                'GIEMS_v2_2020_timezone': 0.0,
                'GIEMS_v2_2020_data_type': 'geo',
                'GIEMS_v2_2020_data_groupby': 'Year',
                'GIEMS_v2_2020_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Inundation/GIEMS_v2_2020/regrid_0.25d/',
                'GIEMS_v2_2020_varname': 'fldfrc',
                'GIEMS_v2_2020_fulllist': '',
                'GIEMS_v2_2020_tim_res': 'Month',
                'GIEMS_v2_2020_varunit': '',
                'GIEMS_v2_2020_geo_res': 0.25,
                'GIEMS_v2_2020_suffix': 'GIEMS_v2_2020_inundation_',
                'GIEMS_v2_2020_prefix': '',
                'GIEMS_v2_2020_syear': 1992,
                'GIEMS_v2_2020_eyear': 2015,
            },
            # 'Pekel': {
            #     'Pekel_timezone': 0.0,
            #     'Pekel_data_type': '',
            #     'Pekel_data_groupby': '',
            #     'Pekel_dir': '/tera11/zhwei/zhwei/Data_ref/geo/',
            #     'Pekel_varname': '',
            #     'Pekel_fulllist': '',
            #     'Pekel_tim_res': '',
            #     '_varunit': '',
            #     'Pekel_geo_res': 0.25,
            #     'Pekel_suffix': '',
            #     'Pekel_prefix': '',
            #     'Pekel_syear': 2000,
            #     'Pekel_eyear': 2001,
            # },
            # 'GIEMS_Papa_2010': {
            #     'GIEMS_Papa_2010_timezone': 0.0,
            #     'GIEMS_Papa_2010_data_type': '',
            #     'GIEMS_Papa_2010_data_groupby': '',
            #     'GIEMS_Papa_2010_dir': '/tera11/zhwei/zhwei/Data_ref/geo/',
            #     'GIEMS_Papa_2010_varname': '',
            #     'GIEMS_Papa_2010_fulllist': '',
            #     'GIEMS_Papa_2010_tim_res': '',
            #     '_varunit': '',
            #     'GIEMS_Papa_2010_geo_res': 0.25,
            #     'GIEMS_Papa_2010_suffix': '',
            #     'GIEMS_Papa_2010_prefix': '',
            #     'GIEMS_Papa_2010_syear': 2000,
            #     'GIEMS_Papa_2010_eyear': 2001,
            # },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Terrestrial_Water_Storage_Anomaly': {
            'GRACE': {
                'GRACE_timezone': 0.0,
                'GRACE_data_type': 'geo',
                'GRACE_data_groupby': 'Single',
                'GRACE_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Terrestrial_Water_Storage_Anomaly/GRACE/',
                'GRACE_varname': 'twsa',
                'GRACE_fulllist': '',
                'GRACE_tim_res': 'Month',
                'GRACE_geo_res': 0.5,
                'GRACE_varunit': 'kg/m2',
                'GRACE_suffix': 'twsa_0.5x0.5',
                'GRACE_prefix': '',
                'GRACE_syear': 2002,
                'GRACE_eyear': 2014,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Snow_Water_Equivalent': {
            'CanSISE': {
                'CanSISE_timezone': 0.0,
                'CanSISE_data_type': 'geo',
                'CanSISE_data_groupby': 'Single',
                'CanSISE_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Snow_Water_Equivalent/CanSISE/',
                'CanSISE_varname': 'swe',
                'CanSISE_fulllist': '',
                'CanSISE_tim_res': 'Month',
                'CanSISE_varunit': 'm',
                'CanSISE_geo_res': 1,
                'CanSISE_suffix': 'swe',
                'CanSISE_prefix': '',
                'CanSISE_syear': 1981,
                'CanSISE_eyear': 2010,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Permafrost': {
            'NSIDC': {
                'NSIDC_timezone': 0.0,
                'NSIDC_data_type': 'geo',
                'NSIDC_data_groupby': 'Single',
                'NSIDC_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Permafrost/NSIDC/',
                'NSIDC_varname': 'permafrost_extent',
                'NSIDC_fulllist': '',
                'NSIDC_tim_res': 'Single',
                'NSIDC_varunit': '1',
                'NSIDC_geo_res': 0.5,
                'NSIDC_suffix': 'NSIDC_0.5x0.5',
                'NSIDC_prefix': '',
                'NSIDC_syear': 2000,
                'NSIDC_eyear': 2000,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Albedo': {
            'GEWEX.SRB': {
                'GEWEX.SRB_timezone': 0.0,
                'GEWEX.SRB_data_type': 'geo',
                'GEWEX.SRB_data_groupby': 'Single',
                'GEWEX.SRB_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Albedo/GEWEX.SRB/monthly/',
                'GEWEX.SRB_varname': 'albedo',
                'GEWEX.SRB_fulllist': '',
                'GEWEX.SRB_tim_res': 'Month',
                'GEWEX.SRB_varunit': 'unitless',
                'GEWEX.SRB_geo_res': 0.5,
                'GEWEX.SRB_suffix': 'Albedo',
                'GEWEX.SRB_prefix': '',
                'GEWEX.SRB_syear': 1984,
                'GEWEX.SRB_eyear': 2007,
            },
            'CERESed4.1': {
                'CERESed4.1_timezone': 0.0,
                'CERESed4.1_data_type': 'geo',
                'CERESed4.1_data_groupby': 'Single',
                'CERESed4.1_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Albedo/CERESed4.1/monthly/',
                'CERESed4.1_varname': 'albedo',
                'CERESed4.1_fulllist': '',
                'CERESed4.1_tim_res': 'Month',
                'CERESed4.1_varunit': '1',
                'CERESed4.1_geo_res': 0.5,
                'CERESed4.1_suffix': 'Albedo',
                'CERESed4.1_prefix': '',
                'CERESed4.1_syear': 2000,
                'CERESed4.1_eyear': 2018,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Upward_SW_Radiation': {
            'CERESed4.1': {
                'CERESed4.1_timezone': 0.0,
                'CERESed4.1_data_type': 'geo',
                'CERESed4.1_data_groupby': 'Single',
                'CERESed4.1_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Upward_SW_Radiation/CERESed4.1/',
                'CERESed4.1_varname': 'rsus',
                'CERESed4.1_fulllist': '',
                'CERESed4.1_tim_res': 'Month',
                'CERESed4.1_varunit': 'W m-2',
                'CERESed4.1_geo_res': 0.5,
                'CERESed4.1_suffix': 'rsus',
                'CERESed4.1_prefix': '',
                'CERESed4.1_syear': 2000,
                'CERESed4.1_eyear': 2018,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Upward_LW_Radiation': {
            'CERESed4.1': {
                'CERESed4.1_timezone': 0.0,
                'CERESed4.1_data_type': 'geo',
                'CERESed4.1_data_groupby': 'Single',
                'CERESed4.1_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Upward_LW_Radiation/CERESed4.1/',
                'CERESed4.1_varname': 'rlus',
                'CERESed4.1_fulllist': '',
                'CERESed4.1_tim_res': 'Month',
                'CERESed4.1_varunit': 'W m-2"',
                'CERESed4.1_geo_res': 0.5,
                'CERESed4.1_suffix': 'rlus',
                'CERESed4.1_prefix': '',
                'CERESed4.1_syear': 2000,
                'CERESed4.1_eyear': 2018,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Net_SW_Radiation': {
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/surface_net_solar_radiation/',
                'ERA5LAND_varname': 'ssr',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'w / m2',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_daymean_surface_net_solar_radiation',
                'ERA5LAND_syear': 1970,
                'ERA5LAND_eyear': 2020,
            },
            'CERESed4.1': {
                'CERESed4.1_timezone': 0.0,
                'CERESed4.1_data_type': 'geo',
                'CERESed4.1_data_groupby': 'Single',
                'CERESed4.1_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Net_SW_Radiation/CERESed4.1/',
                'CERESed4.1_varname': 'rsns',
                'CERESed4.1_fulllist': '',
                'CERESed4.1_tim_res': 'Month',
                'CERESed4.1_varunit': 'W m-2',
                'CERESed4.1_geo_res': 0.5,
                'CERESed4.1_suffix': 'rsns',
                'CERESed4.1_prefix': '',
                'CERESed4.1_syear': 2000,
                'CERESed4.1_eyear': 2018,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Net_LW_Radiation': {
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/surface_net_thermal_radiation/',
                'ERA5LAND_varname': 'str',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'w / m2',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_daymean_surface_net_thermal_radiation',
                'ERA5LAND_syear': 1970,
                'ERA5LAND_eyear': 2020,
            },
            'CERESed4.1': {
                'CERESed4.1_timezone': 0.0,
                'CERESed4.1_data_type': 'geo',
                'CERESed4.1_data_groupby': 'Single',
                'CERESed4.1_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Net_LW_Radiation/CERESed4.1/',
                'CERESed4.1_varname': 'rlns',
                'CERESed4.1_fulllist': '',
                'CERESed4.1_tim_res': 'Month',
                'CERESed4.1_varunit': 'W m-2',
                'CERESed4.1_geo_res': 0.5,
                'CERESed4.1_suffix': 'rlns',
                'CERESed4.1_prefix': '',
                'CERESed4.1_syear': 2000,
                'CERESed4.1_eyear': 2018,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Net_Radiation': {
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/surface_net_radiation/',
                'ERA5LAND_varname': 'Rnet',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'w / qm2',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_daymean_surface_net_radiation',
                'ERA5LAND_syear': 1970,
                'ERA5LAND_eyear': 2020,
            },
            'CERESed4.1': {
                'CERESed4.1_timezone': 0.0,
                'CERESed4.1_data_type': 'geo',
                'CERESed4.1_data_groupby': 'Single',
                'CERESed4.1_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Net_Radiation/CERESed4.1/',
                'CERESed4.1_varname': 'rns',
                'CERESed4.1_fulllist': '',
                'CERESed4.1_tim_res': 'Month',
                'CERESed4.1_varunit': 'W m-2',
                'CERESed4.1_geo_res': 0.5,
                'CERESed4.1_suffix': 'rns',
                'CERESed4.1_prefix': '',
                'CERESed4.1_syear': 2000,
                'CERESed4.1_eyear': 2018,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Ground_Heat_Flux': {
            'CLASS': {
                'CLASS_timezone': 0.0,
                'CLASS_data_type': 'geo',
                'CLASS_data_groupby': 'Single',
                'CLASS_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Ground_Heat_Flux/CLASS/',
                'CLASS_varname': 'hfdsl',
                'CLASS_fulllist': '',
                'CLASS_tim_res': 'Month',
                'CLASS_varunit': 'W m-2',
                'CLASS_geo_res': 0.5,
                'CLASS_suffix': 'hfdsl',
                'CLASS_prefix': '',
                'CLASS_syear': 2003,
                'CLASS_eyear': 2009,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Sensible_Heat': {
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/surface_sensible_heat_flux/',
                'ERA5LAND_varname': 'sshf',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'w / m2',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_daymean_surface_sensible_heat_flux',
                'ERA5LAND_syear': 1970,
                'ERA5LAND_eyear': 2020,
            },
            'FLUXCOM': {
                'FLUXCOM_timezone': 0.0,
                'FLUXCOM_data_type': 'geo',
                'FLUXCOM_data_groupby': 'Single',
                'FLUXCOM_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Sensible_Heat/FLUXCOM/',
                'FLUXCOM_varname': 'sh',
                'FLUXCOM_fulllist': '',
                'FLUXCOM_tim_res': 'Month',
                'FLUXCOM_varunit': 'watt / m2',
                'FLUXCOM_geo_res': 0.5,
                'FLUXCOM_suffix': 'sh',
                'FLUXCOM_prefix': '',
                'FLUXCOM_syear': 1980,
                'FLUXCOM_eyear': 2014,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Diurnal_Temperature_Range': {
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Diurnal_Max_Temperature': {
            'MSWXV100_daily': {
                'MSWXV100_daily_timezone': 0.0,
                'MSWXV100_daily_data_type': 'geo',
                'MSWXV100_daily_data_groupby': 'Day',
                'MSWXV100_daily_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Diurnal_Max_Temperature/MSWXV100/daily/',
                'MSWXV100_daily_varname': 'air_temperature',
                'MSWXV100_daily_fulllist': '',
                'MSWXV100_daily_tim_res': 'Day',
                'MSWXV100_daily_varunit': 'degree_Celsius',
                'MSWXV100_daily_geo_res': 0.1,
                'MSWXV100_daily_suffix': '',
                'MSWXV100_daily_prefix': '',
                'MSWXV100_daily_syear': 1979,
                'MSWXV100_daily_eyear': 2020,
            },
            'MSWXV100_monthly': {
                'MSWXV100_monthly_timezone': 0.0,
                'MSWXV100_monthly_data_type': 'geo',
                'MSWXV100_monthly_data_groupby': 'Month',
                'MSWXV100_monthly_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Diurnal_Max_Temperature/MSWXV100/monthly/',
                'MSWXV100_monthly_varname': 'air_temperature',
                'MSWXV100_monthly_fulllist': '',
                'MSWXV100_monthly_tim_res': 'Month',
                'MSWXV100_monthly_varunit': 'degree_Celsius',
                'MSWXV100_monthly_geo_res': 0.1,
                'MSWXV100_monthly_suffix': '',
                'MSWXV100_monthly_prefix': '',
                'MSWXV100_monthly_syear': 1979,
                'MSWXV100_monthly_eyear': 2020,
            },
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/daymax_2m_temperature/',
                'ERA5LAND_varname': 't2m',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'K',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_daymax_2m_temperature',
                'ERA5LAND_syear': 1970,
                'ERA5LAND_eyear': 2020,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Diurnal_Min_Temperature': {
            'MSWXV100_daily': {
                'MSWXV100_daily_timezone': 0.0,
                'MSWXV100_daily_data_type': 'geo',
                'MSWXV100_daily_data_groupby': 'Day',
                'MSWXV100_daily_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Diurnal_Min_Temperature/MSWXV100/Daily/',
                'MSWXV100_daily_varname': 'air_temperature',
                'MSWXV100_daily_fulllist': '',
                'MSWXV100_daily_tim_res': 'Day',
                'MSWXV100_daily_varunit': 'degree_Celsius',
                'MSWXV100_daily_geo_res': 0.1,
                'MSWXV100_daily_suffix': '',
                'MSWXV100_daily_prefix': '',
                'MSWXV100_daily_syear': 1979,
                'MSWXV100_daily_eyear': 2020,
            },
            'MSWXV100_monthly': {
                'MSWXV100_monthly_timezone': 0.0,
                'MSWXV100_monthly_data_type': 'geo',
                'MSWXV100_monthly_data_groupby': 'Month',
                'MSWXV100_monthly_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Diurnal_Min_Temperature/MSWXV100/Monthly/',
                'MSWXV100_monthly_varname': 'air_temperature',
                'MSWXV100_monthly_fulllist': '',
                'MSWXV100_monthly_tim_res': 'Month',
                'MSWXV100_monthly_varunit': 'degree_Celsius',
                'MSWXV100_monthly_geo_res': 0.1,
                'MSWXV100_monthly_suffix': '',
                'MSWXV100_monthly_prefix': '',
                'MSWXV100_monthly_syear': 1979,
                'MSWXV100_monthly_eyear': 2020,
            },
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/daymin_2m_temperature/',
                'ERA5LAND_varname': 't2m',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'K',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_daymin_2m_temperature',
                'ERA5LAND_syear': 1970,
                'ERA5LAND_eyear': 2020,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Downward_SW_Radiation': {
            'CERESed4.1': {
                'CERESed4.1_timezone': 0.0,
                'CERESed4.1_data_type': 'geo',
                'CERESed4.1_data_groupby': 'Single',
                'CERESed4.1_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Downward_SW_Radiation/CERESed4.1/',
                'CERESed4.1_varname': 'rsds',
                'CERESed4.1_fulllist': '',
                'CERESed4.1_tim_res': 'Month',
                'CERESed4.1_varunit': 'W m-2',
                'CERESed4.1_geo_res': 0.5,
                'CERESed4.1_suffix': 'rsds',
                'CERESed4.1_prefix': '',
                'CERESed4.1_syear': 2000,
                'CERESed4.1_eyear': 2018,
            },
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/surface_solar_radiation_downwards/',
                'ERA5LAND_varname': 'ssrd',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'w / m2',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_ssrd_1D_0p1',
                'ERA5LAND_syear': 1950,
                'ERA5LAND_eyear': 2022,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Downward_LW_Radiation': {
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/surface_thermal_radiation_downwards/',
                'ERA5LAND_varname': 'strd',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'w / m2',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_strd_1D_0p1',
                'ERA5LAND_syear': 1950,
                'ERA5LAND_eyear': 2022,
            },
            'CERESed4.1': {
                'CERESed4.1_timezone': 0.0,
                'CERESed4.1_data_type': 'geo',
                'CERESed4.1_data_groupby': 'Single',
                'CERESed4.1_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Downward_LW_Radiation/CERESed4.1/',
                'CERESed4.1_varname': 'rlds',
                'CERESed4.1_fulllist': '',
                'CERESed4.1_tim_res': 'Month',
                'CERESed4.1_varunit': 'W m-2',
                'CERESed4.1_geo_res': 0.5,
                'CERESed4.1_suffix': 'rlds',
                'CERESed4.1_prefix': '',
                'CERESed4.1_syear': 2000,
                'CERESed4.1_eyear': 2018,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Relative_Humidity': {
            'CRU4.02': {
                'CRU4.02_timezone': 0.0,
                'CRU4.02_data_type': 'geo',
                'CRU4.02_data_groupby': 'Single',
                'CRU4.02_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Relative_Humidity/CRU4.02/',
                'CRU4.02_varname': 'rhums',
                'CRU4.02_fulllist': '',
                'CRU4.02_tim_res': 'Month',
                'CRU4.02_varunit': '%',
                'CRU4.02_geo_res': 0.5,
                'CRU4.02_suffix': 'rhums',
                'CRU4.02_prefix': '',
                'CRU4.02_syear': 1980,
                'CRU4.02_eyear': 2017,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Precipitation': {
            'CMAPv1904': {
                'CMAPv1904_timezone': 0.0,
                'CMAPv1904_data_type': 'geo',
                'CMAPv1904_data_groupby': 'Single',
                'CMAPv1904_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Precipitation/CMAPv1904/',
                'CMAPv1904_varname': 'pr',
                'CMAPv1904_fulllist': '',
                'CMAPv1904_tim_res': 'Month',
                'CMAPv1904_varunit': 'kg m-2 s-1',
                'CMAPv1904_geo_res': 0.5,
                'CMAPv1904_suffix': 'pr',
                'CMAPv1904_prefix': '',
                'CMAPv1904_syear': 1979,
                'CMAPv1904_eyear': 2018,
            },
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/total_precipitation/',
                'ERA5LAND_varname': 'tp',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'm / hr',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_tp_1D_0p1',
                'ERA5LAND_syear': 1950,
                'ERA5LAND_eyear': 2022,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
        'Surface_Air_Temperature': {
            'CRU4.02': {
                'CRU4.02_timezone': 0.0,
                'CRU4.02_data_type': 'geo',
                'CRU4.02_data_groupby': 'Single',
                'CRU4.02_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/Surface_Air_Temperature/CRU4.02/',
                'CRU4.02_varname': 'tas',
                'CRU4.02_fulllist': '',
                'CRU4.02_tim_res': 'Month',
                'CRU4.02_varunit': 'K',
                'CRU4.02_geo_res': 0.5,
                'CRU4.02_suffix': 'tas',
                'CRU4.02_prefix': '',
                'CRU4.02_syear': 1980,
                'CRU4.02_eyear': 2017,
            },
            'ERA5LAND': {
                'ERA5LAND_timezone': 0.0,
                'ERA5LAND_data_type': 'geo',
                'ERA5LAND_data_groupby': 'Year',
                'ERA5LAND_dir': '/tera11/zhwei/zhwei/data/Data_ref/geo_ref/ERA5LAND/daily/air_temperature_2m/',
                'ERA5LAND_varname': 't2m',
                'ERA5LAND_fulllist': '',
                'ERA5LAND_tim_res': 'Day',
                'ERA5LAND_varunit': 'K',
                'ERA5LAND_geo_res': 0.1,
                'ERA5LAND_suffix': 'ERA5LAND_',
                'ERA5LAND_prefix': '_t2m_1D_0p1',
                'ERA5LAND_syear': 1950,
                'ERA5LAND_eyear': 2022,
            },
            'others': {
                '_timezone': 0.0,
                '_data_type': 'geo',
                '_data_groupby': 'Year',
                '_dir': '',
                '_varname': '',
                '_fulllist': '',
                '_tim_res': 'Day',
                '_varunit': '',
                '_geo_res': 0.0,
                '_suffix': '',
                '_prefix': '',
                '_syear': 1980,
                '_eyear': 2024,
            },
        },
    }
    return info
